/* automatically generated by rust-bindgen 0.72.1 */

pub const SENSORS_ERR_WILDCARDS: u32 = 1;
pub const SENSORS_ERR_NO_ENTRY: u32 = 2;
pub const SENSORS_ERR_ACCESS_R: u32 = 3;
pub const SENSORS_ERR_KERNEL: u32 = 4;
pub const SENSORS_ERR_DIV_ZERO: u32 = 5;
pub const SENSORS_ERR_CHIP_NAME: u32 = 6;
pub const SENSORS_ERR_BUS_NAME: u32 = 7;
pub const SENSORS_ERR_PARSE: u32 = 8;
pub const SENSORS_ERR_ACCESS_W: u32 = 9;
pub const SENSORS_ERR_IO: u32 = 10;
pub const SENSORS_ERR_RECURSION: u32 = 11;
unsafe extern "C" {
	pub fn sensors_strerror(errnum: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
	pub static mut sensors_parse_error:
		::std::option::Option<unsafe extern "C" fn(err: *const ::std::os::raw::c_char, lineno: ::std::os::raw::c_int)>;
}
unsafe extern "C" {
	pub static mut sensors_parse_error_wfn: ::std::option::Option<
		unsafe extern "C" fn(
			err: *const ::std::os::raw::c_char,
			filename: *const ::std::os::raw::c_char,
			lineno: ::std::os::raw::c_int,
		),
	>;
}
unsafe extern "C" {
	pub static mut sensors_fatal_error:
		::std::option::Option<unsafe extern "C" fn(proc_: *const ::std::os::raw::c_char, err: *const ::std::os::raw::c_char)>;
}
